# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cuisine', models.CharField(max_length=255)),
                ('takeout', models.BooleanField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='date',
            name='restaurants',
            field=models.ManyToManyField(related_name='dates', to='dojobites_app.Restaurant'),
        ),
        migrations.AddField(
            model_name='date',
            name='users',
            field=models.ManyToManyField(related_name='dates', to='login_reg_app.User'),
        ),
    ]
