# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
        ('dojobites_app', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojobites_app.Restaurant')),
                ('users', models.ManyToManyField(related_name='choices', to='login_reg_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='date',
            name='restaurants',
        ),
        migrations.RemoveField(
            model_name='date',
            name='users',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
