# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojobites_app', '0003_auto_20161026_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='takeout',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
